name: tabs
channels:
  - conda-forge
dependencies:
  - python=3.13
  - rdkit
  - scikit-learn
  - jupyter
  - ca-certificates
  - certifi
  - openssl
  - matplotlib
  - ipywidgets
  - py3Dmol
  - pytest
  - mdtraj
  - pytest-cov
  - tqdm
